### ISSUE TITLE
Remove all mentions

### ISSUE THREAD

**Issue by Revenger** [mikolajkalwa/GamesDealsBot#13]
It's there a command to remove the mention?
I had it set to 'here' and was told it was a bit annoying so I set mention to '@' but not sure how to just remove the mentions without resetting up the bot.

**Comment by mikolajkalwa** [comment]
Hey, it's possible. Please have a look at editwebhook command `gd:help editwebhook`

**Comment by Revenger** [comment]
Seemes I overlooked reading that being half asleep in bed, all good :D
