### ISSUE TITLE
[Suggestion] Ability for the bot to automatically Publish messages in Announcement channels

### ISSUE THREAD

**Issue by Kriper1111** [mikolajkalwa/GamesDealsBot#20]
Since a webhook can't do that by itself, it needs someone to press the button. Or crosspost it [via the API](https://discord.com/developers/docs/resources/channel#crosspost-message).
A hacky solution would be to listen to the target channel and crosspost whatever message the webhook posted, since the actual webhook trigger is on a separate resource.

Could be a nice thing so we won't have to click the "Publish" button every time the bot posts something.

**Comment by mikolajkalwa** [comment]
I think this shouldn't be part of Games Deals Bot itself. In the support server we use separate bot (Games Deals Publisher) which does the "Publish" thing. 
I can make a repository with it if it's useful for you, but you would have to host that bot by yourself.
