### ISSUE TITLE
Help a noob out (can't get the bot to work)

### ISSUE THREAD

**Issue by KungFooZombie** [mikolajkalwa/GamesDealsBot#9]
Hey there! First of all: thank you so much for creating this. A while back I succesfully made the bot work in my own channel with someone there to tell me how to do it. I now have another channel and have to do it on my own. 

Is there a step by step guide anywhere of how to get it to work? I managed to invite the bot, but that;'s all. 
I'm really terrible at stuff like this. 

I read the bot was offline, but on my personal Discord I see it posted Watchdogs 2 for free on the 12th of july. So it does seem to work?

Thanks all!

**Comment by mikolajkalwa** [comment]
Sure thing. Add me on Discord and I'll configure it for you.
Miki#0007

**Comment by KungFooZombie** [comment]
Thanks for the reply. Is there a way I could do it myself, though? I've done it before and may have to do it again for other channels. I'm probably messing up some commands to get the bot into the room I want and function there.

**Comment by mikolajkalwa** [comment]
It's not possible right now. It notifies about the games but the bot  itself is offline. However it'll be back online in a few days.
